# tasks file for installing and updating tools via apt
- name: "updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "upgrade core packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "installing core packages"
  become: true
  become_method: sudo
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - terminator
      - sshfs
      - python3-pyftpdlib
      - gcc-mingw-w64
      - golang
      - ffuf
      - feroxbuster
    state: latest

- name: updating sublime Repository key
  become: true
  become_method: sudo
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: updating APT repository file
  become: true
  become_method: sudo
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    state: present
    filename: sublime

- name: installing and updating sublime text
  become: true
  become_method: sudo
  apt:
    name: sublime-text
    state: present
    update_cache: true
