---
- include_tasks: apt-tools.yml
- include_tasks: kerbrute.yml
- include_tasks: github-repos.yml
- include_tasks: pip-tools.yml
- include_tasks: python-tools.yml
- include_tasks: gem-tools.yml
- include_tasks: get-tools.yml
